name: Release

on:
  workflow_dispatch:
    inputs: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: build binaries
      run: make build-release

    - name: version
      run: echo "::set-output name=version::$(cat VERSION.txt)"
      id: version
    
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: true
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

    # - name: upload linux arm
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./out/mcmods-linux-arm.tar.gz
    #     asset_name: mcmods-linux-arm-${{ steps.version.outputs.version }}.tar.gz
    #     asset_content_type: application/gzip
        
    # - name: upload linux amd
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./out/mcmods-linux-amd.tar.gz
    #     asset_name: mcmods-linux-amd-${{ steps.version.outputs.version }}.tar.gz
    #     asset_content_type: application/gzip

    # - name: upload mac arm
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./out/mcmods-mac-arm.tar.gz
    #     asset_name: mcmods-mac-arm-${{ steps.version.outputs.version }}.tar.gz
    #     asset_content_type: application/gzip

    # - name: upload mac amd
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./out/mcmods-mac-amd.tar.gz
    #     asset_name: mcmods-mac-amd-${{ steps.version.outputs.version }}.tar.gz
    #     asset_content_type: application/gzip

    - name: upload windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./out/mcmods-windows.zip
        asset_name: mcmods-windows-${{ steps.version.outputs.version }}.zip
        asset_content_type: application/zip
